config/routes.rb
Rails.application.routes.draw do
  namespace :auth do
    get 'users/index'
  end
  resources :roles
  
  namespace :auth do
    get 'dashboard/index'
    post 'users/update_roles'

    get 'responses/index'
    get 'responses/show'
    get 'responses/new'
    post 'responses/create'
    get 'responses/edit'
    patch 'responses/update'
    delete 'responses/destroy'

    get 'questions/index'
    get 'questions/show'
    get 'questions/new'
    post 'questions/create'
    get 'questions/edit'
    patch 'questions/update'
    delete 'questions/destroy'


  end

  devise_for :users
  get 'pages/home'

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  has_many :responses
  attachment :zip_file
  attachment :zip_file, content_type: ["application/zip"]

end

app/models/response.rb
class Response < ApplicationRecord

  belongs_to :question
  belongs_to :user
  attachment :zip_file
  attachment :zip_file, content_type: ["application/zip"]

end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_and_belongs_to_many :roles
  
  def has_role(r)
	  self.roles.include?(r)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	include Pundit
	protect_from_forgery
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/_home-jumbotron.html.erb
<div class="jumbotron">
  <h1 class="display-4">BPPWD Support Forum</h1>
  <p class="lead">Access to the BPPWD Support Forum is available to all students in the Programming and Web Development shop at Bay Path
    Regional Vocational Technical High School.  The support forum enables students to post questions regarding shop curriculum and receive
    feedback from peers.  Students will also have access to student created video tutorials and have the ability to post their own videos
    and tutorials to help others. </p>
  <hr class="my-4">
  <p>To get setup with an account, please contact your instructor!</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Request Access</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Support Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-primary">
      <span class="navbar-brand mb-0 h1"><%= link_to "BPPWD.NET", root_url %></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="main-nav">
        <div class="navbar-nav">
          <%= link_to "Home", root_url, class: "nav-item nav-link active" %>
          <% if user_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-item nav-link") %>
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path, class: "nav-item nav-link") %>
            </li>
          <% end %>
        </div>
      </div>
    </nav>
    <% if current_page?(root_url) %>
      <%= render partial: "/layouts/home-jumbotron" %>
    <% end %>
    <div id="main-container" class="container-fluid">
      <div class="row">
        <div class="col">
          <% if alert %>
            <div class="alert alert-danger" role="alert">
              <%= alert %>
            </div>
          <% end %>
          <% if notice %>
            <div class="alert alert-warning" role="alert">
              <%= notice %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
      <footer>
        <div class="row">
          <div class="col-10 m-auto">
            <strong>Admin Pages:</strong>
            <%= link_to "Dashboard", auth_dashboard_index_path %> |
            <%= link_to "Questions", auth_questions_index_path %> |
            <%= link_to "Responses", auth_responses_index_path %> | 
            <%= link_to "Users", auth_users_index_path %> | 
            <%= link_to "Roles", roles_path %>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="col-11 m-auto">
  <h1>Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<div class="col-11 m-auto">
  <h1>Listing All Roles</h1>
  <p><%= link_to 'Add New Role', new_role_path %></p>
  <table class="table table-hover">
  	<thead>
    	<tr>
			<th>Title</th>
			<th></th>
    	</tr>
  	</thead>
    <tbody>
      <% @roles.each do |role| %>
        <tr>
          <th scope="row"><%= role.title %></th>
          <td>
	          <% if role.title != "administrator" %>
	          	<%= link_to 'Show', role %> | 
			  	<%= link_to 'Edit', edit_role_path(role) %> | 
			  	<%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %>
			  <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @role.title %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>